### PR TITLE
Forum mention

### PR DESCRIPTION
**Pull request by Hasel2278**
Fix https://github.com/simple-login/website/issues/108

### CODE REVIEW

**Comment by Hasel2278** [comment]
@nguyenkims on this https://github.com/simple-login/website/pull/107/commits/32ae4141ae39392dfef833fd5ce2c8fa80e32148 commit I done that because you already have one link to GitHub repo, so I don’t think duplication of it is necessary.

On this https://github.com/simple-login/website/pull/107/commits/da1554c5e239ecf4abd1851b59ec3a3539aa3b6a commit I put it in another section as you mentioned in discussion with another user [here](https://github.com/simple-login/website/pull/106#discussion_r1434057994)

On this https://github.com/simple-login/website/pull/107/commits/35917c2b342c7fcc775b433ad44e6bc842bac562 I just added the same as previous user.

On this https://github.com/simple-login/website/pull/107/commits/fba1a1ca78e32ae4511a847be25ac38b27894c1b I just changed `is not` to `isn’t` I think it is looking better now

**Comment by Hasel2278** [comment]
@nguyenkims on this https://github.com/simple-login/website/pull/107/commits/32ae4141ae39392dfef833fd5ce2c8fa80e32148 commit I done that because you already have one link to GitHub repo, so I don’t think duplication of it is necessary.

On this https://github.com/simple-login/website/pull/107/commits/da1554c5e239ecf4abd1851b59ec3a3539aa3b6a commit I put it footer

On this https://github.com/simple-login/website/pull/107/commits/35917c2b342c7fcc775b433ad44e6bc842bac562 I just added forum mention.

On this https://github.com/simple-login/website/pull/107/commits/fba1a1ca78e32ae4511a847be25ac38b27894c1b I just changed `is not` to `isn’t` I think it is looking better now

**Comment by Hasel2278** [comment]
**Why it is important?**
For now this forum is not really popular, so it’s better to increase it popularity. That’s why:
- It is open source. Users who care about privacy will like this.
- It is not filled with Microsoft tracking (GitHub owned by Microsoft so Microsoft _can_ track your activity on GitHub)
- Some users don’t want to use GitHub because it is flagging accounts created with SimpleLogin alias. It is totally privacy intrusion.

**Comment by Ping5784** [comment]
@nguyenkims, are you here? :)

**Comment by nguyenkims** [comment]
I see, the update will be visible in the next deployment :)

**Pull request merged**
